// <auto-generated />
namespace EntityLINQ.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class addednewcontent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednewcontent));
        
        string IMigrationMetadata.Id
        {
            get { return "201404082147128_addednewcontent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
